version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - golang
      - nodejs
    networks:
      - app-network

  golang:
    image: brh-backend:1.0
    container_name: golang
    ports:
      - "8080:8080"
    networks:
      - app-network

  nodejs:
    image: node-app
    container_name: nodejs
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
